### PR TITLE
Expose the `sqlite3_update_hook` callback

### PR DESCRIPTION
**Pull request by tantaman**
Useful for getting data change notifications on write.

### Checklist
- [x] I grant to recipients of this Project distribution a perpetual,
non-exclusive, royalty-free, irrevocable copyright license to reproduce, prepare
derivative works of, publicly display, sublicense, and distribute this
Contribution and such derivative works.
- [x] I certify that I am legally entitled to grant this license, and that this
Contribution contains no content requiring a license from any third party.

### CODE REVIEW

**Comment by linhttbk97** [comment]
@tantaman can you resolve the conflicts

**Comment by alii** [comment]
What was the reason this was closed for? I think this would be a really welcome addition. Is there any way someone could potentially take lead of this instead and perhaps look at getting it merged? thanks a lot :)

**Comment by rhashimoto** [comment]
I don't know why @tantaman closed it, but I'm making significant internal changes for a [new release](https://github.com/rhashimoto/wa-sqlite/discussions/153), and callback handling is one of the things affected. I probably won't be merging much of anything except important bug fixes (particularly new callbacks) until the new release is ready.

**Comment by alii** [comment]
Got it, thanks! Would these changes allow for triggers? In a similar fashion to this

https://github.com/WiseLibs/better-sqlite3/issues/62#issuecomment-325797335

**Comment by rhashimoto** [comment]
@alii Unless I'm missing something, the comment you link describes a technique that uses `sqlite3_create_function` instead of `sqlite3_update_hook`. wa-sqlite already provides a [wrapper](https://rhashimoto.github.io/wa-sqlite/docs/interfaces/SQLiteAPI.html#create_function) for that.

**Comment by xyc** [comment]
Is there any interest in re-opening this PR? `sqlite3_update_hook` would enable many reactive / local first app use cases.

For example, the implementation of `useLiveQuery` in expo-sqlite uses the update hook:

https://github.com/expo/expo/blob/75172f0339d707a685c60e72e70a7ce4e90c9080/packages/expo-sqlite/ios/SQLiteModule.swift#L433-L457

**Pull request closed without merging**
