### PR TITLE
Expose `sqlite3_update_hook`

### PR DESCRIPTION
**Pull request by hazelmeow**
This PR adds support for `sqlite3_update_hook`.

### Checklist
- [x] I grant to recipients of this Project distribution a perpetual,
non-exclusive, royalty-free, irrevocable copyright license to reproduce, prepare
derivative works of, publicly display, sublicense, and distribute this
Contribution and such derivative works.
- [x] I certify that I am legally entitled to grant this license, and that this
Contribution contains no content requiring a license from any third party.

### CODE REVIEW

**Comment by hazelmeow** [comment]
@rhashimoto I see that CI failed on "Test with checked-in WASM files". Should I build and commit new WASM files? The output I get (for the js at least) is significantly different from what's checked in right now.

**Comment by rhashimoto** [comment]
Sure, let's try that. What version of Emscripten are you using? I think what is checked in now was built with 3.1.47 so if you're using something significantly more current then that might explain why things are so different.

**Comment by hazelmeow** [comment]
I'm using emcc 3.1.66. I pushed a commit with a new `dist/` built so hopefully that passes CI, but it feels a little wrong to me to have binaries compiled by someone random (me) on master...

**Comment by rhashimoto** [comment]
I agree. That's one reason I asked for your Emscripten version - to try to duplicate the built bytes before merging.

Ah, the tests work now! I'll do the security check the next time I have free cycles.

**Comment by rhashimoto** [comment]
My build is byte for byte identical on 3.1.66. Local testing failed, which was resolved by upgrading Chromium in my development container from 122 to 129. I think the problem was [changes in the JSPI API](https://v8.dev/blog/jspi-newapi) that caused the Chromium and Emscripten versions to be out of step. Curiously, the GitHub CI action is still using Chromium 121 and that works, but JSPI support has been evolving behind a flag so it isn't unbelievable.

Thanks for the PR!

**Pull request merged**
